### ISSUE TITLE
"maps/d1_trainstation_01 not found"

### ISSUE THREAD

**Issue by vladiun321** [Pinsplash/halflife2chaos#105]
Then i start the game from new game button and the i choosing the first chapter it didnt loaded and loading a map direcly didnt work
perhaps i only have that issue

1. Go to 'New Gme'
2. Click on 'Point insection'
3. And then i see error in the console map didnt found

the version was on v.0..3.4

there is a video is showing 
https://github.com/Pinsplash/halflife2chaos/assets/168669701/4db47ee7-7ef5-419d-96ac-157a53ad47ea

**Comment by daniel5-cpu** [comment]
Did you managed to fix it ? im having the same issue

**Comment by vladiun321** [comment]
> Did you managed to fix it ? im having the same issue

Yeah i just put the mod in sourcemods in c disk

**Comment by daniel5-cpu** [comment]
ok, thx for the fast reply 👍
