### ISSUE TITLE
Add aimbot effect

### ISSUE THREAD

**Issue by joaopinto24** [Pinsplash/halflife2chaos#106]
**Describe the solution you'd like**
There's a hud element tied to autoaim, I have not messed with it before so I don't know how possible this is, but the effect would make the autoaim extreme and automatically hold down shoot but the player's view remains in the same place, the effect could add another crosshair, like the airboat gun to show what its aiming at

**Additional context**
There's a very similar effect in the gta V chaos mod

**Comment by Pinsplash** [comment]
autoaim-ish thing planned already
