### ISSUE TITLE
Base Half Life 2 Launching Instead

### ISSUE THREAD

**Issue by PerlsteinPineapple** [Pinsplash/halflife2chaos#109]
I have the same issue as #66

**Comment by acuifex** [comment]
Are you sure that you've downloaded and installed the [release (v0.3.4 hl2c.zip)](https://github.com/Pinsplash/halflife2chaos/releases/download/v0.3.4/hl2c.zip)?

All of the mod's logic is in `client.dll` and `server.dll`, and using the base game's dlls would probably get you this issue

**Comment by PerlsteinPineapple** [comment]
Yeah, I was having all these issues because I downloaded the wrong one, thanks.
