### ISSUE TITLE
Content not being mounted

### ISSUE THREAD

**Issue by GrigoriSpankov** [Pinsplash/halflife2chaos#110]
HL2 has no maps and the Episodes are missing textures. I don't know why this is happening as it was working before. I have my Sourcemods folder installed on D: and linked to C: via symbolic link. HL2 and Episodes installed in D:.

**Comment by acuifex** [comment]
iirc we discussed this with pin before, and HL2 has to be in the same install destination as sourcemods, or in the default one. I don't remember exactly. Try symlinking HL2's folder somewhere around `..\..\common\Half-Life 2\episodic` from the view of hl2chaos

**Comment by GrigoriSpankov** [comment]
I'm not exactly the most tech-literate man, so could you run that process by me in a more detailed manner, please?

**Comment by acuifex** [comment]
If hl2chaos is installed at `D:\sourcemods\hl2chaos` and linked with a symbolic link to `C:\Program Files (x86)\Steam\steamapps\sourcemods\hl2chaos`
and hl2 is installed at `D:\steamLibrary\steamapps\common\Half-Life 2`, 
then you should either make a symbolic link from `D:\steamLibrary\steamapps\common\Half-Life 2` to `C:\Program Files (x86)\Steam\steamapps\common\Half-Life 2`
or try moving hl2chaos from `D:\sourcemods\hl2chaos` into `D:\steamLibrary\sourcemods\hl2chaos`

**Comment by GrigoriSpankov** [comment]
That worked. Thanks!
