### ISSUE TITLE
chaos_replace_bullets_with_crossbow doesn't work

### ISSUE THREAD

**Issue by randomultrakillplayer** [Pinsplash/halflife2chaos#114]
**Describe the bug**
bullets can't get replaced by crossbow

**To Reproduce**
open the console, turn cheats on, enter the command

**Expected behavior**
bullets get replaced by crossbow

**Additional context**
using the newest version

**Comment by Pinsplash** [comment]
the feature was never coded to begin with actually, so...

**Comment by randomultrakillplayer** [comment]
bruh
