### ISSUE TITLE
How to play on Linux?

### ISSUE THREAD

**Issue by supervitu64** [Pinsplash/halflife2chaos#115]
problem is in the title

**Comment by acuifex** [comment]
https://files.catbox.moe/2nh98m.xz
I've compiled for linux at the current master version (https://github.com/Pinsplash/halflife2chaos/commit/9ca8f74abab562d4dabca8802dd1a5f85e944169)
Textures seem fucked for ep2 (probably because i don't have it downloaded)
And also make sure you install base hl2 in the same location as the source mod. i.e. `~/.steam/steam/steamapps/common/Half-Life 2` if installing the mod in `~/.steam/steam/steamapps/common/sourcemods/hl2chaos`. This is, imo, a poor choice by pin that i've asked to change.

btw pin, drop step 5 from compilation https://github.com/Pinsplash/halflife2chaos#building-from-source-for-linux, it seems to put the bin files where it should now

**Comment by supervitu64** [comment]
doesn't work

**Comment by acuifex** [comment]
Probably because of linked libraries. I use arch, so they're very recent. I guess you'll have to compile it yourself

**Comment by supervitu64** [comment]
nevermind, putting the `hl2chaos` folder in `custom` makes it work
not sure if that's intended but it does work

**Comment by supervitu64** [comment]
also may i ask what are the commands for the grenade weapons of HL2 but the guns shoot grenades video?

**Comment by acuifex** [comment]
https://github.com/Pinsplash/halflife2chaos/issues/92#issuecomment-2002052061
i think it's described here

**Comment by supervitu64** [comment]
`chaos_` commands throw a command not found error

**Comment by acuifex** [comment]
https://github.com/Pinsplash/halflife2chaos/issues/34
The mod _NEEDS_ its custom client and server binaries.
For linux you can just follow these steps, excluding step 5: https://github.com/Pinsplash/halflife2chaos#building-from-source-for-linux
If you want episodic too, you can add `client_episodic server_episodic` to the end of the `make` command (step 4), and then also repeating step 6 with `ep1chaos` and `ep2chaos` instead of `hl2chaos`

**Comment by supervitu64** [comment]
bulding from source throws errors upon doing the make part

**Comment by acuifex** [comment]
I don't know what kind of error are you having, but see if https://github.com/Pinsplash/halflife2chaos/issues/62 helps you

**Comment by supervitu64** [comment]
`Building: tier1
Building: mathlib
Building: vgui_controls
make[1]: se entra en el directorio '/home/supervitu64/halflife2chaos/sp/src/mathlib'
make[1]: se entra en el directorio '/home/supervitu64/halflife2chaos/sp/src/vgui2/vgui_controls'
make[1]: se entra en el directorio '/home/supervitu64/halflife2chaos/sp/src/tier1'
---- 3dnow.cpp ----
---- almostequal.cpp ----
---- bitbuf.cpp ----
---- filesystem_helpers.cpp ----
In file included from /usr/lib/gcc/x86_64-linux-gnu/13/include/limits.h:205,
                 from /usr/lib/gcc/x86_64-linux-gnu/13/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/13/include/limits.h:34,
                 from /home/supervitu64/halflife2chaos/sp/src/vgui2/vgui_controls/../../public/filesystem.h:8,
                 from /home/supervitu64/halflife2chaos/sp/src/vgui2/vgui_controls/../../public/filesystem_helpers.cpp:7:
/usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No existe el archivo o el directorio
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/include/c++/13/cmath:41,
                 from /usr/include/c++/13/math.h:36,
                 from /home/supervitu64/halflife2chaos/sp/src/mathlib/3dnow.cpp:7:
/usr/include/c++/13/bits/requires_hosted.h:31:10: fatal error: bits/c++config.h: No existe el archivo o el directorio
   31 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [vgui_controls_linux32.mak:141: obj_vgui_controls_linux32/release/filesystem_helpers.o] Error 1
make[1]: se sale del directorio '/home/supervitu64/halflife2chaos/sp/src/vgui2/vgui_controls'
make[1]: *** [mathlib_linux32.mak:86: obj_mathlib_linux32/release/3dnow.o] Error 1
make[1]: *** Se espera a que terminen otras tareas....
---- byteswap.cpp ----
make: *** [sp/src/games.mak:60: vgui_controls] Error 2
make: *** Se espera a que terminen otras tareas....
---- characterset.cpp ----
In file included from /usr/include/c++/13/cmath:41,
                 from /usr/include/c++/13/math.h:36,
                 from /home/supervitu64/halflife2chaos/sp/src/public/mathlib/mathlib.h:10,
                 from /home/supervitu64/halflife2chaos/sp/src/public/tier1/bitbuf.h:19,
                 from /home/supervitu64/halflife2chaos/sp/src/tier1/bitbuf.cpp:9:
/usr/include/c++/13/bits/requires_hosted.h:31:10: fatal error: bits/c++config.h: No existe el archivo o el directorio
   31 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/include/c++/13/cmath:41,
                 from /usr/include/c++/13/math.h:36,
                 from /home/supervitu64/halflife2chaos/sp/src/mathlib/almostequal.cpp:10:
/usr/include/c++/13/bits/requires_hosted.h:31:10: fatal error: bits/c++config.h: No existe el archivo o el directorio
   31 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [tier1_linux32.mak:104: obj_tier1_linux32/release/bitbuf.o] Error 1
make[1]: *** Se espera a que terminen otras tareas....
make[1]: *** [mathlib_linux32.mak:94: obj_mathlib_linux32/release/almostequal.o] Error 1
make[1]: se sale del directorio '/home/supervitu64/halflife2chaos/sp/src/mathlib'
make: *** [sp/src/games.mak:40: mathlib] Error 2
In file included from /usr/include/c++/13/cmath:41,
                 from /usr/include/c++/13/math.h:36,
                 from /home/supervitu64/halflife2chaos/sp/src/public/mathlib/vector.h:16,
                 from /home/supervitu64/halflife2chaos/sp/src/public/datamap.h:15,
                 from /home/supervitu64/halflife2chaos/sp/src/public/tier1/byteswap.h:13,
                 from /home/supervitu64/halflife2chaos/sp/src/tier1/byteswap.cpp:8:
/usr/include/c++/13/bits/requires_hosted.h:31:10: fatal error: bits/c++config.h: No existe el archivo o el directorio
   31 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [tier1_linux32.mak:112: obj_tier1_linux32/release/byteswap.o] Error 1
In file included from /home/supervitu64/halflife2chaos/sp/src/tier1/characterset.cpp:14:
/usr/include/string.h:26:10: fatal error: bits/libc-header-start.h: No existe el archivo o el directorio
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [tier1_linux32.mak:120: obj_tier1_linux32/release/characterset.o] Error 1
make[1]: se sale del directorio '/home/supervitu64/halflife2chaos/sp/src/tier1'
make: *** [sp/src/games.mak:56: tier1] Error 2
`

**Comment by acuifex** [comment]
yeah, seems similar to #62. if you're on a debian based distro, i think `sudo apt-get install gcc-multilib` should fix this

**Comment by supervitu64** [comment]
multilib is already installed

**Comment by supervitu64** [comment]
i think i found the issue, had to install `g++-multilib`

**Comment by supervitu64** [comment]
it's done compiling but when i click "Play" on the mod nothing happens

**Comment by acuifex** [comment]
no idea. try adding `%command% > /tmp/chaos.log 2> /tmp/chaos.err` to see logs.

**Comment by supervitu64** [comment]
to hl2 or chaos?

**Comment by acuifex** [comment]
Chaos. hl2 is only used for its resources

**Comment by supervitu64** [comment]
i have a .err file (1,4kb) and a .log file (0kb) on /tmp

**Comment by supervitu64** [comment]
.err says the following:
`x86_64-linux-gnu-capsule-capture-libs: warning: we are assuming "_el_fn_sh_complete" to be private, but it's just a guess
i386-linux-gnu-capsule-capture-libs: warning: we are assuming "_el_fn_sh_complete" to be private, but it's just a guess
pressure-vessel-wrap[48510]: N: Not replacing "/etc/vulkan/explicit_layer.d" with tmpfs: Path "/etc" is reserved by the container framework
pressure-vessel-wrap[48510]: N: Not replacing "/etc/vulkan/implicit_layer.d" with tmpfs: Path "/etc" is reserved by the container framework
Proton: Upgrading prefix from None to 9.0-202 (/home/supervitu64/.steam/debian-installation/steamapps/compatdata/243730/)
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
Setting breakpad minidump AppID = 243730
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561199172174151 [API loaded no]
wine: using kernel write watches, use_kernel_writewatch 1.`

**Comment by acuifex** [comment]
it's running with proton for some reason, but other than that, i don't see what's wrong. try disabling proton, i don't have any more ideas.

**Comment by supervitu64** [comment]
steam console spews the following 4 times before closing the game:
src/clientdll/compatmanager.cpp (1107) : CCompatManager::GetCompatibilityToolCommandLineInternal: invoked with invalid parameters.

**Comment by supervitu64** [comment]
OH MY GOD IT WORKS NOW
i had to install Source SDK Base 2007
