### ISSUE TITLE
Mod doesn't want to work and doesn't throw any error, but console won't open normally and forcing it open throws a script error

### ISSUE THREAD

**Issue by E-Bommel** [Pinsplash/halflife2chaos#118]
**Describe the bug**
I can't get the mod running and thought maybe I can prod around with the console, but even though it is enabled in the settings, the dev console won't open, no matter which key I bind it to (it does seem to make the lil hud sound though) and forcing it to open via the starting properties (-console) throws the following python script error:
[Unknown Script] poll unexpected exception: invalid literal for int() with base 10: 'Unknown command "chaos_vote_internal_poll"'
It also won't recognzie chaos commands in that state
Without the console property there is no error, but the mod also doesn't do anything even though it's definitely connected (closing the game throws me the script error that the network end is gone)

**To Reproduce**
No script error, but no console
 - Start the game like normal
Console but script error
 - Start the game with -console

**Expected behavior**
Mod and console work

**Additional context**
Just wanna stream episode 1 chaos like I did with base HL2, dunno what made things not work anymore and I can't prod cause the console won't work
I tried HL2 base and it won't work anymore either
already replaced the whole mod with a newly downloaded pack, reran the twitch integration setup where it only has issues with the script import, but I manually imported the current script anyway, I'm outta ideas

**Comment by acuifex** [comment]
> but even though it is enabled in the settings, the dev console won't open

Weird. I think i sometimes get this with other games. You can try `-condebug` instead to dump the console into a `console.log` file in the mod folder.

> Unknown command "chaos_vote_internal_poll"'

Sounds to me like the mod binaries are missing. See if anything here helps: https://github.com/Pinsplash/halflife2chaos/issues/34 (also see back-references)

**Comment by E-Bommel** [comment]
> Weird. I think i sometimes get this with other games. You can try -condebug instead to dump the console into a console.log file in the mod folder.
I can't seem to find a log file in the whole sourcemods folder even after starting the game with that parameter

> Sounds to me like the mod binaries are missing. See if anything here helps: https://github.com/Pinsplash/halflife2chaos/issues/34 (also see back-references)
deleted every folder and copied a fresh install over and all the maps from the game into the maps folder, no changes sadly

**Comment by E-Bommel** [comment]
here's a screenshot of the console when I force it open btw, maybe it helps
![image](https://github.com/user-attachments/assets/4a67b51b-a5ac-40f3-98d9-b08855ac115b)

**Comment by acuifex** [comment]
Other than "Steam config directory" being half-life 2 instead of sdk 2013 singleplayer, i've got basically no idea. 

I can only suggest all of the silly things like checking if `client.dll` and `server.dll` are in `sourcemods/ep1chaos/bin/`, or if sdk is installed and stuff.

I could hop on for a discord screen share if you want to, but no guarantees i can actually figure this out since i'm on linux lol. @ acuifex on there.

**Comment by acuifex** [comment]
Solution: User issue. He was starting `Half-Life 2` instead of the mod `HL2 Chaos vX.X.X`

**Comment by E-Bommel** [comment]
I have brought shame to my family and will now explode into confetti for I am a clown
