### ISSUE TITLE
Not showing up in Steam

### ISSUE THREAD

**Issue by DorianMoreno00** [Pinsplash/halflife2chaos#120]
As you can see in the title, the mod just doesn't show up in Steam even after restarting it and downloading the zip file again.  The weird part is that i followed correctly the instructions of how to install but it only shows the episodes one and two.

**Comment by supervitu64** [comment]
did you put all 3 folders on sourcemods or the one containing them

**Comment by DorianMoreno00** [comment]
> did you put all 3 folders on sourcemods or the one containing them

i put all of them in sourcemods.

**Comment by supervitu64** [comment]
you gotta put the hl2chaos, ep1chaos and ep2chaos on the sourcemods folder

**Comment by DorianMoreno00** [comment]
> you gotta put the hl2chaos, ep1chaos and ep2chaos on the sourcemods folder

They're already on the folder, the problem is that only the episodes appear in Steam instead of the Base game (Normal Hal-life 2)

**Comment by Pinsplash** [comment]
i made a list of all the installation problems people have had so far https://github.com/Pinsplash/halflife2chaos/discussions/121

**Comment by DorianMoreno00** [comment]
> i made a list of all the installation problems people have had so far #121

Ok, thank you so much Pinsplash you are a life saver 👍

**Comment by DorianMoreno00** [comment]
> i made a list of all the installation problems people have had so far #121

So...i found out that Steam Only accepts One "Version" of the Mod, either the episodes or the base game. And apparently since the 3 folders where in Sourcemod, Steam only recognized 2  for some reason (the episodes). But now that i deleted those, it recognizes the Base game and it appears as is supposed to.

**Comment by Pinsplash** [comment]
doesn't make sense but alright
