### ISSUE TITLE
npc_blob nearly working

### ISSUE THREAD

**Issue by Pinsplash** [Pinsplash/halflife2chaos#13]
Blobs don't look good right now because they use a model for their appearance, not metaballs. I recently saw someone put metaballs in gmod, so surely it's possible to do in hl2.

**Comment by DrPeeper228** [comment]
metaballs in gmod are created by mee(the same guy who created the infinite map)

**Comment by Pinsplash** [comment]
69867b14
marching cubes are working, but metaballs are currently totally screwed it seems?

**Comment by Pinsplash** [comment]
shape is done, need to optimize it still

**Comment by Pinsplash** [comment]
that was surprisingly easy? so now i have to make the texture look right...
