### ISSUE TITLE
Asset assertion fail or something idk

### ISSUE THREAD

**Issue by DrPeeper228** [Pinsplash/halflife2chaos#23]
!(this)[https://i.imgur.com/PMETLio.png]

**Comment by DrPeeper228** [comment]
> were you noclipping or something during this, cause the error message suggests you were going really really fast

yeah, i was noclipping, but in the teleporter cutscene at red letter day so i can't go really fast so idk

**Comment by Pinsplash** [comment]
Well I tried that myself and no asserts came up. Closing because not enough info.

**Comment by DrPeeper228** [comment]
interesting, i should note: the cutscene didn't play well because i exited the trigger with supoerspeed to kill Breen but i exited the trigger so the cutscene stopped working properly, that's when i started noclipping
