### ISSUE TITLE
Can't launch game, says "Engine Error: Could not load library client. Try restarting. If that doesn't work, verify the cache."

### ISSUE THREAD

**Issue by TheodoreFSharpe** [Pinsplash/halflife2chaos#29]
When trying to launch the mod with all the appropriate map files installed, the game simply crashes upon start and says "Could not load library client. Try restarting. If that doesn't work, verify the cache."

**Comment by Pinsplash** [comment]
Did you download it from the Releases page?
Did you set 2013 SDK to "upcoming"?

**Comment by TheodoreFSharpe** [comment]
I'm embarassed to say that no, I did not download from the release page. I did set the 2013 SDK to upcoming though.

I got it working. Apologies for the inconvenience!
