### ISSUE TITLE
Could not load library client error

### ISSUE THREAD

**Issue by Nakerbottt** [Pinsplash/halflife2chaos#34]
**Describe the bug**
Got the "could not load library client" error message

**To Reproduce**
Followed the instructions but got this error

**Comment by acuifex** [comment]
> and copy server.dll and client.dll from SourceSDK Base 2013/sourcetest/bin

Can't say for the other issues, but the `sourcetest/bin` files are likely a clean client. Mod's client gets written into [sp/game/mod_hl2/bin](https://github.com/Pinsplash/halflife2chaos/tree/main/sp/game/mod_hl2/bin) after compiling, and all of the necessary resources for running are in [sourcemods/hl2chaos](https://github.com/Pinsplash/halflife2chaos/tree/main/sourcemods/hl2chaos)

**Comment by AgroDaCheese** [comment]
This fixed it. Thanks.

**Comment by Nakerbottt** [comment]
yes that worked! Thank you
