### ISSUE TITLE
Add effect "back/frontflip"

### ISSUE THREAD

**Issue by joaopinto24** [Pinsplash/halflife2chaos#40]
**Is your feature request related to a problem? Please describe.**
I found the command and i thought it would be fun to have it here

**Describe the solution you'd like**
Add new effect possibly called backflip/frontflip, which removes the max amount you can look up or down, possible implementation being executing `cl_pitchup 360` and `cl_pitchdown 360` on the client if possible

**Describe alternatives you've considered**
Also making player spin briefly would be fun (or annoying) too.

**Additional context**
gif below demonstaring what i mean because im bad at explenations

![gif gif](https://user-images.githubusercontent.com/132157779/235315919-bbe3d7aa-f3f6-45f0-8f69-c365da81a1be.gif)

**Comment by Pinsplash** [comment]
something kind of like this is already planned
