### ISSUE TITLE
Mod can't load library client

### ISSUE THREAD

**Issue by vapx5** [Pinsplash/halflife2chaos#46]
**Describe the bug**
When I try to launch the mod (HL2, ep1, ep2) it starts and shows the valve thingy after that this 
![Screenshot 2023-05-11 190838](https://github.com/Pinsplash/halflife2chaos/assets/125921875/17b401ee-a6c7-49c5-bb48-bb8882f26f6a)  
pops up 

**To Reproduce**
1. Launch "HL2 Chaos v0.2.3" or "HL:EP1 Chaos v0.2.3"
2. see the error message

**Comment by acuifex** [comment]
see if https://github.com/Pinsplash/halflife2chaos/issues/34 helps

**Comment by vapx5** [comment]
That helped, Thank you!
