### ISSUE TITLE
Default keybinds are wrong?

### ISSUE THREAD

**Issue by Pinsplash** [Pinsplash/halflife2chaos#49]
Somehow, people seem to keep getting my personal keybinds, even though the mod no longer ships a config.cfg and every other bind-related file looks normal.

The most obvious ones are mwheel on jump and save and load on m and n.

Look at basically any video of hl2 chaos on youtube.

**Comment by acuifex** [comment]
`cfg/config.cfg` is still in the release zip. it's created automatically whenever you launch the game.
you might want to [reset the local repository](https://stackoverflow.com/a/42903805) before building and releasing

**Comment by Pinsplash** [comment]
oh thats tru
