### ISSUE TITLE
shooting with teleporter bullets shows blue arrow things

### ISSUE THREAD

**Issue by joaopinto24** [Pinsplash/halflife2chaos#57]
**Describe the bug**
shooting with teleporter bullets effect active draws objets with a line towrds players prevoius positioin and position to be teleported to
**To Reproduce**
1. have teleporter bullets enabled
2. shoot
3. profit i guess??

**Expected behavior**
**(Not needed if it's something obvious, like you expected the game to not crash.)**

**Additional context**
0.2.6 is the version
![image](https://github.com/Pinsplash/halflife2chaos/assets/132157779/90ef0d5c-6bd0-48a1-be1c-47050f4af7f9)

**Comment by Pinsplash** [comment]
Already fixed, will be coming in the next release.
