### ISSUE TITLE
Trying to build for linux doesn't work (Missing .h files?)

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [Pinsplash/halflife2chaos#62]
**Describe the bug**
Trying to build for Ubuntu 22.0.4.
running the "make -f ./sp/src/games.mak -j$(grep processor /proc/cpuinfo | wc -l) client_hl2 server_hl2"
command errors with many fatal errors, stating "No such file or directory"

**To Reproduce**
Try to build the mod from source according to the instructions.
-> Fails with Compilation errors "File Not found"

**Additional context**
Error log: https://pastebin.com/z5CQD6da

**Comment by acuifex** [comment]
seems like you're missing some std libs, try answers from here: https://stackoverflow.com/questions/54082459/fatal-error-bits-libc-header-start-h-no-such-file-or-directory-while-compili

**Comment by DisruptionSystemsINC** [comment]
> seems like you're missing some std libs, try answers from here: https://stackoverflow.com/questions/54082459/fatal-error-bits-libc-header-start-h-no-such-file-or-directory-while-compili

Thank you very much, that fixed it
