### ISSUE TITLE
Linux From-Source-Build: Cannot Open Maps 

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [Pinsplash/halflife2chaos#65]
**Describe the bug**
On Ubuntu 22.04 LTS, and when built from source, the main menu will not work correctly i.e The "New game" menu will pop up, but upon selecting the map it will close and the map will not load

**To Reproduce**
1. Build the chaos mod from source (V1.2.9) according to the instructions
2. Start the mod
3. Start a new game
4. Upon selecting a map, nothing happens

**Expected behavior**
Start the selected chapter

**Additional context**

V1.2.9
Ubuntu 22.04 LTS

**Comment by acuifex** [comment]
this is due to missing map files.
since i haven't really played the campaign and don't even have the base game downloaded, i don't know how the map searching works.

if you have hl2 downloaded, you can either `ln -s` the entire `maps` folder or copy all `.bsp` files from hl2.
if you don't have it downloaded, you can use something like [DepotDownloader](https://github.com/SteamRE/DepotDownloader) to download only map files like this:
```bash
# add a regex to match only map files
echo "regex:.+\.bsp" > /tmp/filelist.txt

# download maps into "/tmp/hl2/hl2/maps/*.bsp". the total size is 778M
depotdownloader -app 220 -depot 221 -filelist /tmp/filelist.txt -dir /tmp/hl2 -username <USERNAME>
```

**Comment by DisruptionSystemsINC** [comment]
Thank you very much, that fixed it!

**Comment by acuifex** [comment]
please keep the issue open. the mod is supposed to find map files by itself.

**Comment by Pinsplash** [comment]
do you have hl2 installed? it's supposed to pull the maps from HL2

**Comment by DisruptionSystemsINC** [comment]
Half life 2 is installed.
The log output is:


pGameDir hl2chaos
szPath /home/disruption/.steam/debian-installation/steamapps/common/Half-Life 2
\hl2

**Comment by acuifex** [comment]
i think this is due to this https://stackoverflow.com/a/19490200

change it to what the code bellow does:
```
V_AppendSlash( szPath, sizeof(szPath) );
V_strncat( szPath, "hl2", sizeof( szPath ) );
```

**Comment by Pinsplash** [comment]
hopefully the latest release fixed this?

**Comment by Pinsplash** [comment]
no follow up, presuming it's been fixed
