### ISSUE TITLE
Unknown commands in console

### ISSUE THREAD

**Issue by C4MUG** [Pinsplash/halflife2chaos#66]
**Describe the bug**
In loaded game there nothing of chaos mod and in console writes Unknown command "chaos" and everything what have "chaos_

**To Reproduce**
1. Add client.dll and server.dll from Sourse SDK Base 2013 singleplayer into bin of hl2chaos. Cuz in hl2chaos didnt have bin
2. Start new game
3. Open console
4. Scroll up to 'Unknown command "chaos"'
5. See error

**Additional context**
V
![Untitled](https://github.com/Pinsplash/halflife2chaos/assets/114811351/2af63996-800a-4b36-adc9-6a25e36ce29d)

**Comment by acuifex** [comment]
hello, does #34 work for you?

**Comment by C4MUG** [comment]
"could not load library client" fixed, but chaos command dont work

**Comment by RadFox34** [comment]
Hey there how did you fix this? i'm getting this same problem.
