### ISSUE TITLE
Twitch Integration script does not update Text object

### ISSUE THREAD

**Issue by 0x5066** [Pinsplash/halflife2chaos#67]
**Describe the bug**
When playing with the Twitch Integration enabled as per the instructions, the assigned Text object in OBS does not update at all while the game is running, this can be observed by continuously running `chaos_vote_debug` and watching the Text object. To get it up to date you'll have to reload the script, which loses all votes as well.

**To Reproduce**
1. Start both OBS and HL2 Chaos (as per the instructions and launch parameter)
2. Play game
3. ???
4. Text objects never update, aside from getting the votes and never clearing them (the game still receives the votes, and they are stuck because they are never cleared)

**Expected behavior**
None of that? I saw it used to work in someones VOD but that seems to be a while ago.

**Additional context**
~~Add any other context about the problem here. A video showing what happened leading up to the issue is most useful. Also state the mod version number (eg v0.2.2).~~

**Comment by KoverUnderCover** [comment]
also have this problem

**Comment by 0x5066** [comment]
A relief to know I'm not the only one then!

**Comment by Pinsplash** [comment]
@acuifex 

this line is in the script log

> [Unknown Script] poll failed [WinError 1225] The remote computer refused the network connection

**Comment by acuifex** [comment]
> The remote computer refused the network connection

sounds like the client doesn't start the rcon server.

i've also seen a streamer have issues, and i think it's a logic bug. i'll try to check what's up later

**Comment by Pinsplash** [comment]
actually i think that was because i was launching the game without the necessary launch parameters.

**Comment by Pinsplash** [comment]
i've just realized i can't find any place where g_iVoteNumber is incremented @acuifex

**Comment by Pinsplash** [comment]
yep gonna commit soon
