### ISSUE TITLE
It's not starting up

### ISSUE THREAD

**Issue by Sixteen60** [Pinsplash/halflife2chaos#68]
It just leads to this error. I did what the error said, and even reinstalled the mod but it still isn't working.
![Screenshot 2023-08-06 204043](https://github.com/Pinsplash/halflife2chaos/assets/99849136/eb417f16-ff09-4721-9c52-40fedf3bebbc)
How else should I fix this?

**Comment by Pinsplash** [comment]
Have you looked at #29 and #34?

**Comment by Pinsplash** [comment]
no update, presuming fixed
