### ISSUE TITLE
Progress bar doesn't line up with aspect ratios besides 16:9

### ISSUE THREAD

**Issue by Darah1l** [Pinsplash/halflife2chaos#69]
**Describe the bug**
On 2560x1080 resolution the progress bar behaves as if it were 1920x1080, i. e. it fills up from 1st pixel up to 1920th. I would imagine the same problem exists on 3440x1440; perhaps also on other non16/9 resolutions.

**To Reproduce**
N/A

**Expected behavior**
The progress uses the whole horizontal space and considers the last pixel of the monitor/window as the 100% state.

**Additional context**

https://github.com/Pinsplash/halflife2chaos/assets/141714529/c48faad9-0257-47d3-81cc-96384df9a180

V.0.2.10

**Comment by Pinsplash** [comment]
no update, presuming fixed
