### ISSUE TITLE
my monitor turns off when i start up the thing

### ISSUE THREAD

**Issue by idontknowwhattoputhere0** [Pinsplash/halflife2chaos#74]
it just turns off what do i do

**Comment by acuifex** [comment]
does it still happen in windowed mode (`-windowed`)? if so, i'd guess it's a driver issue, otherwise it could be a hardware issue.
i also had my monitor turn off and back on from a specific video with a specific gpu. didn't happen with another gpu.

**Comment by Pinsplash** [comment]
whatever this is, there's no way it's within control of this mod

**Comment by idontknowwhattoputhere0** [comment]
> does it still happen in windowed mode (`-windowed`)? if so, i'd guess it's a driver issue, otherwise it could be a hardware issue. i also had my monitor turn off and back on from a specific video with a specific gpu. didn't happen with another gpu.

i tried to run it in windowed and now it works, thanks a lot!
