### ISSUE TITLE
mod wont work

### ISSUE THREAD

**Issue by lamprosxd** [Pinsplash/halflife2chaos#76]
When I launch the mod I see in the console "chaos" is unknown command

**reproduce**
1. launch the game/mod
2. check the console

**context**
Im using the linux build and I have copied the maps from hl2 maps folder and the game runs like normal hl2

**Comment by acuifex** [comment]
Sounds similar to this https://github.com/Pinsplash/halflife2chaos/issues/34#issuecomment-1522307095

Are you sure that you've followed the linux build instructions correctly? https://github.com/Pinsplash/halflife2chaos#building-from-source-for-linux

**Comment by lamprosxd** [comment]
> Sounds similar to this [#34 (comment)](https://github.com/Pinsplash/halflife2chaos/issues/34#issuecomment-1522307095)
> 
> Are you sure that you've followed the linux build instructions correctly? https://github.com/Pinsplash/halflife2chaos#building-from-source-for-linux

yes I did everything correctly,but I fixed it with installing source sdk base and sdk 2007 idk why that worked.
