### ISSUE TITLE
HL2 Chaos v0.2.11 won't appear in my Steam library (Windows)

### ISSUE THREAD

**Issue by ConeBride** [Pinsplash/halflife2chaos#77]
I followed the instructions but couldn't get to the point of it appearing in the library -_- 

Not sure if it's relevant, but I had other mod pre-installed earlier "Raising the Bar" and it would work. I thought that it might interfere with Chaos mod so I deleted it along with SDK and then re-installed Source SDK Base 2013 just to be sure, which did not help.

Screenshot of Source SDK Base 2013 Singleplayer and Half-life 2 installed
![image](https://github.com/Pinsplash/halflife2chaos/assets/144689053/1a3c360d-b898-49e6-87fb-53899ed53404)

Screenshot of installed mod path
![image](https://github.com/Pinsplash/halflife2chaos/assets/144689053/07a98d08-9239-4fd4-83c8-a83b573ff4ef)

**Comment by acuifex** [comment]
Have you restarted steam after installing?

**Comment by ConeBride** [comment]
Yeah, not only that but restarted PC several times as well.

**Comment by acuifex** [comment]
It's hard to say what's wrong. I think it's something with steam. Try playing with library filter options? Maybe it's hiding it for some reason

If you don't figure it out, you can try and adapt this linux script for windows:
```bash
#!/bin/bash

pushd "/home/acuifex/.local/share/Steam/steamapps/common/Source SDK Base 2013 Singleplayer/"
STEAMRUNTIME="$HOME/.local/share/Steam/ubuntu12_32/steam-runtime"
export LD_LIBRARY_PATH="/usr/lib:/usr/lib32:$STEAMRUNTIME/lib/i386-linux-gnu/:$STEAMRUNTIME/usr/lib/i386-linux-gnu/:$LD_LIBRARY_PATH"
export SteamEnv=1
./hl2.sh -game sourcetest -steam -game /home/acuifex/.local/share/Steam/steamapps/sourcemods/hl2chaos
popd
```

**Comment by ConeBride** [comment]
Thanks! It was indeed in hidden for some reason Owo

wasn't even aware that "hidden" option exists o((>ω< ))o

**Comment by acuifex** [comment]
Please close the issue if it's solved
