### ISSUE TITLE
The options (Source text, target channel, rcon password) don't appear in OBS

### ISSUE THREAD

**Issue by elmemeee** [Pinsplash/halflife2chaos#81]
**Describe the bug**
The options (Source text, target channel, rcon password) don't appear in OBS. I opened the script in Notepad++ to change said settings and the twitch integration still doesn't work
**To Reproduce**
1. Already have Python installed
2. Do the normal installation process.
3. The options don't show on OBS
4. The voting doesn't work

**Expected behavior**
Options do appear in OBS, without the need for me to open the file, and Twitch integration works

**Additional context**
I have the latest version as of 12-11-2023 (DD/MM/YYYY)

**Comment by elmemeee** [comment]
Oh, and I have OBS 27.0.1

**Comment by acuifex** [comment]
I think there were issues with the older obs which were fixed (python 3.11 support in 29.1 beta 1?). Consider upgrading obs and checking that you have a new-ish python (3.11 or newer iirc)

**Comment by elmemeee** [comment]
ok, thanks for the fast reply

**Comment by Pinsplash** [comment]
No follow up, assuming fixed.
