### ISSUE TITLE
Port it to nillerusr's srceng

### ISSUE THREAD

**Issue by stephen-cusi** [Pinsplash/halflife2chaos#85]
[source-engine](https://github.com/nillerusr/source-engine)

**Comment by thecatontheceiling** [comment]
> why

I have no clue why these people even bother asking

**Comment by ItzVladik** [comment]
@stephen-cusi i did it

**Comment by ItzVladik** [comment]
> why

androd support i think

**Comment by stephen-cusi** [comment]
> @stephen-cusi i did it

**👌🏻**

**Comment by ItzVladik** [comment]
> > @stephen-cusi i did it
> 
> **👌🏻**

But i have so many crasher trying to fix
