### ISSUE TITLE
Some engine error. I don't anything about Source

### ISSUE THREAD

**Issue by Hrudai-Devain** [Pinsplash/halflife2chaos#92]
When I launched the game after setting things up, the game showed the intro then got an engine error.

The version is 0.3.0 and here is the picture

![image_2024-03-16_183422830](https://github.com/Pinsplash/halflife2chaos/assets/145323711/e40c129d-5aa2-4fb7-8e9b-8efcbb30187c)

**Comment by acuifex** [comment]
Sounds like a #29 and #34 duplicate. Are you downloading the [release](https://github.com/Pinsplash/halflife2chaos/releases)?

**Comment by Hrudai-Devain** [comment]
Yeah, I pressed on the latest one that said Release.

**Comment by acuifex** [comment]
If you followed the [installation](https://github.com/Pinsplash/halflife2chaos#installing) correctly, then my only suggestion is to restart steam. The error is usually caused by the engine not being able to find the game libraries in `sourcemods/hl2chaos/bin/*.dll`

**Comment by Hrudai-Devain** [comment]
Should sourcemods be empty for it to work?

**Comment by acuifex** [comment]
I think it works well with other mods installed at the same time. Just make sure the hl2chaos is installed cleanly

**Comment by Hrudai-Devain** [comment]
Still bore no fruit.

**Comment by Hrudai-Devain** [comment]
So, I saw a comment on one error that was the same as this one and then saw that you need a bin folder for the game to work, the only problem I have is what files to download. Can you tell their names?

**Comment by acuifex** [comment]
`client.dll` and `server.dll`. Both of them should be included in the `hl2c.zip` release file

**Comment by Hrudai-Devain** [comment]
Where?

**Comment by acuifex** [comment]
[hl2c.zip v0.3.0 release](https://github.com/Pinsplash/halflife2chaos/releases/download/v0.3.0/hl2c.zip) path inside archive: `/hl2c/hl2chaos/bin/`

**Comment by Hrudai-Devain** [comment]
I am such a idiot, I deserve to be clowned on. I downloaded halflife2chaos-main.zip instead of hl2c.zip.

**Comment by Hrudai-Devain** [comment]
I am gonna check if this works. If I update and the coast is clear then its good to close.

**Comment by Hrudai-Devain** [comment]
Alright, I have good news and bad news. The good news is that the game launches, the bad news is that my camera is on LSD.

**Comment by acuifex** [comment]
> the bad news is that my camera is on LSD.

Sounds like an intended feature. Have fun

**Comment by Hrudai-Devain** [comment]
If its an intended feature then why does it stay on different maps and does not have a name on the right.

**Comment by acuifex** [comment]
¯\\_(ツ)_/¯
Probably a bug. Not sure. Haven't launched this mod in a while

**Comment by Hrudai-Devain** [comment]
Nvm fixed it. And also do you have any idea how to get that grenade guns thing forever and no other events happen, like Pinsplash's video. You can give a reply with an idea or say no then close it.

**Comment by acuifex** [comment]
`chaos_replace_bullets_with_grenades 1` or `chaos_test_effect <id>` with id from `chaos_print` i think.
`chaos 0` to disable automatic effect selection iirc.

> You can give a reply with an idea or say no then close it.

I don't have any permissions in this repo. The `Contributor` thing is because i've got a commit in the repository
